@startuml ucase-reservations
skinparam actorStyle hollow

actor Trésorier
actor Administrateur

Administrateur <- Trésorier

rectangle Réservations {
  usecase valide
  usecase crée
  usecase édite
  usecase supprime
  usecase liste
}

Trésorier --> valide
Trésorier --> crée
Trésorier --> édite
Trésorier --> supprime
Trésorier --> liste
@enduml