@startuml ucase-exposant-reservation
skinparam actorStyle hollow

actor Exposant

rectangle Réservations {
  usecase "réserve N tables" as réserve
  usecase consulte
  usecase "demande annulation" as annule
}

Exposant --> réserve
Exposant --> consulte
Exposant --> annule
@enduml